### ISSUE TITLE
Unhandled REPL handler exception processing message

### ISSUE THREAD

**Issue by NickeZ** [pinealan/niddle#2]
Hey again,

I get this backtrace when I connect with the conjure vim plugin to the nrepl server. Not sure if this is a problem in niddle, but niddle is in the trace..

```
nREPL server started on port 32913 on host localhost - nrepl://localhost:32913
(ns conjure.internal (:require [clojure.pprint :as pp]))
ERROR: Unhandled REPL handler exception processing message {:code #?(:clj 'clj :cljs 'cljs :cljr 'cljr :default 'unknown), :id 3a319bc2-0aea-43ab-b825-a09bc01078e7, :op eval, :session 37f307d0-e15a-447f-ba0a-b51029447431}
java.lang.RuntimeException: Conditional read not allowed
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.LispReader$ConditionalReader.checkConditionalAllowed(LispReader.java:1623)
        at clojure.lang.LispReader$ConditionalReader.invoke(LispReader.java:1627)
        at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:853)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.read(LispReader.java:216)
        at clojure.lang.LispReader.read(LispReader.java:205)
        at clojure.lang.RT.readString(RT.java:1878)
        at clojure.lang.RT.readString(RT.java:1873)
        at clojure.core$read_string.invokeStatic(core.clj:3815)
        at clojure.core$read_string.invoke(core.clj:3805)
        at niddle.print$read_form.invokeStatic(print.clj:79)
        at niddle.print$read_form.invoke(print.clj:79)
        at niddle.print$printable_form.invokeStatic(print.clj:88)
        at niddle.print$printable_form.invoke(print.clj:87)
        at niddle.print$eval3892$fn__3894.invoke(print.clj:92)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at niddle.print$niddle_mw$fn__3914.invoke(print.clj:126)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.middleware.caught$wrap_caught$fn__926.invoke(caught.clj:97)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.middleware.print$wrap_print$fn__893.invoke(print.clj:234)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.server$default_handler$fn__1586.invoke(server.clj:130)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
        at nrepl.server$handle_STAR_.invoke(server.clj:19)
        at nrepl.server$handle$fn__1557.invoke(server.clj:39)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
conjure.internal=> nil
```

**Comment by pinealan** [comment]
Thanks for reporting. Fixed in #3
